### ISSUE TITLE
Failure on generate

### ISSUE THREAD

**Issue by justgage** [jessitron/elm-template#7]
I was trying to generate an Elm project and got the following errors after installing via instructions in the repo:
```
λ ~/code/ rug generate jessitron:elm-rugs:StaticPage admin-ui-elm
Created default configuration file at /Users/justgage/.atomist/cli.yml
Processing dependencies
  Downloading jessitron/elm-rugs/maven-metadata.xml ← rugs (0kb) succeeded
```
... a bunch of downloads....
```
Loading jessitron:elm-rugs:2.0.0 into runtime failed

com.atomist.project.archive.ProjectOperationArchiveReader.findOperations(Lcom/atomist/source/ArtifactSource;Lscala/Option;Lscala/collection/Seq;Lscala/Function1;)Lcom/atomist/project/archive/Operations;
```

**Comment by russmiles** [comment]
This looks like a Rug version issue, what version of the Rug CLI are you using @justgage ?

In the meantime I'll see if there's anything obvious to fix.

**Comment by russmiles** [comment]
Also this is a set of deprecated Rugs now; the latest set are available from  http://github.com/jessitron/elm-rugs

Could you switch to those @justgage ?

**Comment by justgage** [comment]
```
λ ~/code/review_rocket/ master* rug -v
rug 0.18.1
atomist/rug-cli.git (git revision 70504cf; last commit 2016-12-19)
```
I'll upgrade on brew. Not sure how to use updated rugs. I thought those were the ones I used...

**Comment by justgage** [comment]
Update it seems to be working 👍
